### ISSUE TITLE
product and division should not produce same unit

### ISSUE THREAD

**Issue by jackhftang** [momeemt/Unit#1]
For example, `3.cm * 3.cm` should be 9 cm^2, not `9.cm`

**Comment by JohnAD** [comment]
I like that idea. Such that:

```nim
# calculate area:
assert 3.0.m * 4.0.m == 12.0.m2
# stack three parts:
assert 3.0 * 4.0.m == 12.0.m
# calculate velocity:
assert 3.0.s * 4.0.m == 12.0.mps
```

I'm not sure how many combinations you want to support, but I like the idea.

**Comment by jackhftang** [comment]
I am thinking something like this, but the downside is that it check the unit at runtime and raise exception. It would be nice to have compile time check, but it is not obvious to me on how to implement compile time check in a reasonable way. 

```nim
import strformat

type
  Si* = enum
    siS = "s",
    siM = "m",
    siKg = "kg",
    siA = "A",
    siK = "K",
    siMol = "mol",
    siCd = "cd",

  Unit* = array[Si,int8]

  Quantity*[T: SomeNumber] = object
    quantity: T
    unit: Unit

proc `$`*(unit: Unit): string =
  var d, q: string
  for u,n in unit:
    if n == 1: d.add $u
    elif n > 1: d.add fmt"{u}^{n}"
    elif n == -1: q.add $u
    elif n < -1: q.add fmt"{u}^{-n}"
  result.add d
  if q.len > 0:
    result.add "/"
    result.add q
  
proc `$`*[T](quantity: Quantity[T]): string =
  result.add $quantity.quantity
  result.add $quantity.unit

proc `==`*(a,b: Unit): bool =
  for i in Si:
    if a[i] != b[i]: return false
  return true

proc `+`*[T](a,b: Quantity[T]): Quantity[T] =
  if a.unit != b.unit:
    raise newException(ValueError, "Cannot + with different units")
  Quantity[T](
    quantity: a.quantity + b.quantity, 
    unit: a.unit
  )

proc `*`*[T](a: T, u: Unit): Quantity[T] = Quantity[T](quantity: a, unit: u)

proc `+`*(a, b: Unit): Unit = 
  for i in Si:
    result[i] = a[i] + b[i]

proc `-`*(a, b: Unit): Unit = 
  for i in Si:
    result[i] = a[i] - b[i]

proc `*`*[T](a: T, b: Quantity[T]): Quantity[T] =
  Quantity[T](
    quantity: a * b.quantity, 
    unit: b.unit
  )

proc `*`*[T](a, b: Quantity[T]): Quantity[T] =
  Quantity[T](
    quantity: a.quantity * b.quantity, 
    unit: a.unit + b.unit
  )

proc `/`*[T](a, b: Quantity[T]): Quantity[T] =
  Quantity[T](
    quantity: a.quantity / b.quantity, 
    unit: a.unit - b.unit
  )

const
  m = block:
    var u: Unit
    u[siM] = 1
    u

  s =  block:
    var u: Unit
    u[siS] = 1
    u

  cm = 0.01 * m

let a = 3.0*m
let b = 4.0*cm
let c = 5.0*s
assert sizeof(Unit) == 7
assert $a == "3.0m"
assert $b == "0.04m"
assert $(a + b) == "3.04m"
assert $(a * b) == "0.12m^2"
assert $(a / c) == "0.6m/s"
assert $(a / c / c) == "0.12m/s^2"

```

**Comment by JohnAD** [comment]
A compile-time check, even in theory, would be challenging. For example:

```nim
var x = 3.0 * m
x = x * (4.0 * m)
assert $x == "12.0m^2"
```

Essentially, the "type" of x just changed during run-time.

Myself, I'm okay with it being a run-time characteristic.

Perhaps, a programmer could enforce results purposefully at compile-time:

```nim
var x = staticUnit(3.0, m)
var acc = staticUnit(9.3, m / (s ^ 2))
```

In that scenario, the `x = x * 4.0*m` would generate a compile-time error.

or alternatively enforce at run-time with:

```nim
var x = 3.0 * m
assert x.verifyUnit(m)
x = x * (4.0 * m)
assert x.verifyUnit(m ^ 2)
assert x.verifyUnit(m * m)
```

**Comment by JohnAD** [comment]
Or, and I'm sort of wildly speculating here, have a direct assignment be static as it is now but a multiple be a run-time assignment:

Static:

```nim
var x = 3.0.m
# any change to units of "x" generates a compile-time error.
```

Dynamic:

```nim
var x = 3.0 * m
# any change of units of "x" is tracked and is checkable.
```

To do that, the `m` should have to be a macro. When passed without a parameter it would behave one way, but when passed an `int` or `float` it would behave a different way. I'd have to do some sample code to determine the viability of that.


(edit: having just typed this, I'm not sure if this would make the library subtly confusing.)

**Comment by momeemt** [comment]
I wasn't able to come up with the best implementation for this problem, so @jackhftang 's and @JohnAD 's advice and reimplemented the new one.
It's a cool and clean implementation so I'm very impressed.

Thanks to #1 , I don't have to create a new type anymore, but as mentioned above, the inability to detect type errors and I thought that the equality of scalar multiples and type declaration operators could cause some confusion in use I've been thinking about these two issues for a while.
I will make a major version when I've resolved them.

If you are also interested in "Unit", we welcome issues and PullRequest! 
Thank you so much!

**Comment by jackhftang** [comment]
Actually, I realize that it is not hard to apply some code generation technique to generate types for static check, but I don't have time to code it now. Anyway, I think the core problem is the programming interface. People like "Unit" because of its simple interface, I think no rush to break interface now. 3.cm * 3.cm = 9.cm maybe make sense in some case =]
