### ISSUE TITLE
Possible combo library

### ISSUE THREAD

**Issue by JohnAD** [momeemt/Unit#3]
I am inspired by this library. There might be some very useful applications in engineering, machining/CNC, and laboratory settings.

In fact, I've been thinking there might be use for a "meta" library that inherits from both this library and my Decimal library. Gaining the benefit of unit tracking and precision tracking.

These are just thoughts for now. The Decimal library is very much still in beta.

**Comment by momeemt** [comment]
That's very exciting!

I actually developed "Unit" to develop a physics library, so Decimal library to develop one powerful "meta" library, it would help a lot of Nim developers I think it can contribute to those who
Apparently, "Unit" has most of the features envisioned by #1 (of course (there is still room for improvement), so it looks like you can start developing the "meta" library I hope you'll let me know when you're in!
